# Generated by Django 4.0.6 on 2022-07-06 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('content', models.CharField(max_length=1024)),
                ('dateOfCreation', models.DateTimeField()),
                ('isArchive', models.BooleanField(default=False)),
            ],
        ),
    ]
